include classpath("application.conf")

node-address {
  protocol = http
  host = "*"
  port = 9324
  context-path = ""
}

queues {
  deploy-events {
    defaultVisibilityTimeout = 60
    delay = 0
    receiveMessageWait = 20
    deadLettersQueue {
      name = "deploy-events-dlq"
      maxReceiveCount = 3
    }
  }
  deploy-events-dlq {
    defaultVisibilityTimeout = 60
    delay = 0
    receiveMessageWait = 20
  }
}
